apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: thanos-receive-default
  namespace: thanos
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: thanos-receive-default
  maxReplicas: 20
  minReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
